spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

  mail:
    host: smtp.gmail.com
    port: 587
    username: temupxan@gmail.com
    password: pmgkvavhundymzok
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true