version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres-lagunagym
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: temirkhan322
      POSTGRES_DB: lagunagym
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    container_name: flyway-lagunagym
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=temirkhan322
      - FLYWAY_URL=jdbc:postgres://postgres:5432/lagunagym?currentSchema=boot
    command: -locations=filesystem://flyway/sql migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
      -
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  ХЗ пока не уверен, хотел же в кубернетес выпустить MSA