version: '3.8'

services:
  auth-postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: temirkhan322
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  user-postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: temirkhan322
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"
    volumes:
      - user-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  membership-postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: temirkhan322
      POSTGRES_DB: membershipdb
    ports:
      - "5434:5432"
    volumes:
      - membership-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  flyway-auth:
    image: flyway/flyway:latest
    container_name: flyway-auth
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=temirkhan322
      - FLYWAY_URL=jdbc:postgresql://auth-postgres:5432/authdb?currentSchema=boot
    command: -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./auth-service/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - auth-postgres
    networks:
      - microservices-network

  flyway-user:
    image: flyway/flyway:latest
    container_name: flyway-user
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=temirkhan322
      - FLYWAY_URL=jdbc:postgresql://user-postgres:5432/userdb?currentSchema=boot
    command: -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./user-service/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - user-postgres
    networks:
      - microservices-network

  flyway-membership:
    image: flyway/flyway:latest
    container_name: flyway-membership
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=temirkhan322
      - FLYWAY_URL=jdbc:postgresql://membership-postgres:5432/membershipdb?currentSchema=boot
    command: -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./membership-service/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - membership-postgres
    networks:
      - microservices-network

  eureka-server:
    build:
      context: ./eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    volumes:
      - ./src:/build/src
      - ./target:/build/target

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8082:8082"
    depends_on:
      - flyway-auth
      - eureka-server
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=localhost:9092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-postgres:5432/authdb?currentSchema=boot
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=temirkhan322
      - JWT_SECRET=52f8f8f95212e347b9cabedb65734e30962c6a627e773c75a63125c52a6c13a2
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - microservices-network
    volumes:
      - ./src:/build/src
      - ./target:/build/target
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8083:8083"
    depends_on:
      - flyway-user
      - eureka-server
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-postgres:5432/userdb?currentSchema=boot
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=temirkhan322
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - microservices-network
    volumes:
      - ./src:/build/src
      - ./target:/build/target
  membership-service:
    build:
      context: ./membership-service
    container_name: membership-service
    ports:
      - "8084:8084"
    depends_on:
      - flyway-membership
      - eureka-server
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=localhost:9092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://membership-postgres:5432/membershipdb?currentSchema=boot
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=temirkhan322
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - microservices-network
    volumes:
      - ./src:/build/src
      - ./target:/build/target
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8765:8765"
    environment:
      - JWT_SECRET=52f8f8f95212e347b9cabedb65734e30962c6a627e773c75a63125c52a6c13a2
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - auth-service
      - user-service
      - membership-service
      - eureka-server
    networks:
      - microservices-network
    volumes:
      - ./src:/build/src
      - ./target:/build/target
  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8088:8088"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=localhost:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - zookeeper
      - kafka
      - eureka-server
    networks:
      - microservices-network
    volumes:
      - ./src:/build/src
      - ./target:/build/target

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - microservices-network

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - microservices-network

volumes:
  auth-postgres-data:
  user-postgres-data:
  membership-postgres-data:

networks:
  microservices-network:
    driver: bridge
