spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: membership-service
          uri: lb://membership-service
          predicates:
            - Path=/memberships/**
          filters:
            - PrefixPath=/api
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - PrefixPath=/api
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /auth-service/v3/api-docs
        name: Auth Service
      - url: /user-service/v3/api-docs
        name: User Service
      - url: /membership-service/v3/api-docs
        name: Membership Service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765

jwt:
  secret: 52f8f8f95212e347b9cabedb65734e30962c6a627e773c75a63125c52a6c13a2
