spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: membership-service
          uri: ${MEMBERSHIP-SERVICE_URI:http://localhost:8084}
          predicates:
            - Path=/memberships/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, Temoxa Gateway Service
        - id: auth-service
          uri: ${AUTH_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/api/auth/**

server:
  port: 8765

jwt:
  secret: 52f8f8f95212e347b9cabedb65734e30962c6a627e773c75a63125c52a6c13a2
