server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/membershipdb?currentSchema=boot
    username: postgres
    password: temirkhan322
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration
  application:
    name: membership-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

jwt:
  secret: 52f8f8f95212e347b9cabedb65734e30962c6a627e773c75a63125c52a6c13a2
