server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/userdb?currentSchema=boot
    username: postgres
    password: temirkhan322
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

jwt:
  secret: 52f8f8f95212e347b9cabedb65734e30962c6a627e773c75a63125c52a6c13a2

