

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/baattezu/demo-config-server
          clone-on-start: true



server:
  port: 8090